export const VENUE_TYPES = [
    'Hall',
    'Beach',
    'Farmhouse',
    'Outdoor' ,
    'Ballroom', 
    'Garden',
    'Lawn',
    'Rooftop',
    'Banquet', 
    'Marquee'];

export const CITIES = [
    'Karachi', 
    'Lahore', 
    'Islamabad', 
    'Multan',
    'Peshawar', 
    'Quetta', 
    'Faisalabad', 
    'Rawalpindi', 
    'Sialkot', 
    'Gujranwala', 
    'Hyderabad', 
    'Sukkur', 
    'Bahawalpur', 
    'Sargodha', 
    'Sahiwal', 
    'Dera Ghazi Khan', 
    'Mardan', 
    'Swat', 
    'Chitral', 
    'Gilgit', 
    'Skardu']